[versions]
precompose = "1.6.2"
snakeyaml = "2.6"
gson = "2.13.2"
kermit = "2.1.0"
maleficextensions = "1.4.4"
dokka = "2.1.0"
kotlin = "2.4.10"
kotlinter = "5.4.2"
vanniktech = "0.36.0"
material3 = "1.9.0"

[libraries]
precompose = { module = "moe.tlaster:precompose", version.ref = "precompose" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
malefic-ext-compose = { module = "xyz.malefic:ext-compose", version.ref = "maleficextensions" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
compose-kotlin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
